/**
 * SKU 카탈로그 속성(attrs) 표시용 라벨/순서 정의입니다.
 */

export const COMMON_ATTRIBUTE_KEYS: string[] = ['color', 'style', 'pattern'];

export const ATTRIBUTE_LABELS: Record<string, string> = {
  base_type: '베이스 유형',
  bed_type: '침대 유형',
  chair_type: '의자 유형',
  color: '색상',
  door_type: '도어 유형',
  drawer_count: '단수',
  features: '특징',
  firmness: '경도',
  frame_material: '프레임 소재',
  frame_type: '프레임 유형',
  has_armrest: '팔걸이 유무',
  has_backrest: '등받이 유무',
  has_drawer: '서랍 유무',
  has_frame: '프레임 유무',
  has_headboard: '헤드보드 유무',
  has_headrest: '헤드레스트 유무',
  has_legs: '다리 유무',
  has_mirror: '거울 유무',
  has_stool: '스툴 포함 여부',
  has_storage: '수납 유무',
  has_wheels: '바퀴 유무',
  head_type: '헤드 유형',
  installation_type: '설치 방식',
  layout_type: '레이아웃 유형',
  leg_type: '다리 유형',
  length: '길이',
  level_count: '단수',
  material: '소재',
  mattress_type: '매트리스 유형',
  mobility_type: '이동 방식',
  pattern: '패턴',
  product_type: '제품 유형',
  seating_capacity: '인승수',
  shape: '형태',
  shelf_count: '단수',
  shelf_type: '선반 유형',
  size: '사이즈',
  sofa_type: '소파 유형',
  storage_features: '수납 특징',
  storage_type: '유형',
  style: '스타일',
  thickness: '두께',
  top_material: '상판 소재',
  tv_stand_type: '유형',
  vanity_type: '유형',
  wardrobe_type: '옷장 유형',
  wood_tone: '우드톤',
};

export const CATEGORY_ATTRIBUTE_FIELDS: Record<string, string[]> = {
  '거실장·TV장': [
    'tv_stand_type',
    'length',
    'material',
    'level_count',
    'has_legs',
  ],
  거울: ['installation_type', 'shape', 'has_frame'],
  '서랍·수납장': [
    'storage_type',
    'drawer_count',
    'material',
    'has_legs',
    'has_wheels',
    'has_drawer',
    'wood_tone',
  ],
  선반: ['shelf_type', 'material', 'frame_material', 'shelf_count'],
  소파: [
    'sofa_type',
    'material',
    'has_legs',
    'has_armrest',
    'has_headrest',
    'has_stool',
  ],
  의자: ['chair_type', 'material', 'has_wheels', 'has_backrest', 'has_armrest'],
  '진열장·책장': ['storage_type', 'material', 'frame_material', 'door_type'],
  침대: [
    'bed_type',
    'size',
    'has_headboard',
    'frame_type',
    'material',
    'base_type',
    'product_type',
    'wood_tone',
    'head_type',
  ],
  '테이블·식탁·책상': [
    'shape',
    'top_material',
    'frame_material',
    'leg_type',
    'has_storage',
    'wood_tone',
    'seating_capacity',
  ],
  매트리스: ['mattress_type', 'size', 'thickness', 'features', 'firmness'],
  '행거·옷장': [
    'layout_type',
    'mobility_type',
    'door_type',
    'storage_features',
    'material',
    'wardrobe_type',
  ],
  '화장대·콘솔': ['vanity_type', 'has_mirror', 'storage_type', 'material'],
};
